name: store

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
    ports:
      - 5432:5432

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: store
      MYSQL_DATABASE: store
      MYSQL_USER: store
      MYSQL_PASSWORD: store
    ports:
      - 3306:3306
