server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: store
    password: store
    driver-class-name: org.postgresql.Driver
